  import cron from "node-cron";
import { db } from "@workspace/db";
import {
  tasksTable,
  usersTable,
  notificationsTable,
  holidaysTable,
  complianceItemsTable,
  complianceStatusTable,
  complianceCompaniesTable,
  appSettingsTable,
  taskTransfersTable,
} from "@workspace/db";
import { eq, and, ne, sql, isNotNull, isNull, inArray, lt } from "drizzle-orm";
import { computeDueDate, periodKeyForDate, istToday, ymd } from "@workspace/compliance-dates";
import { sendDailyDigestEmail, sendReminderEmail, sendDashboardEmail } from "./emailService";
import { periodKey, istDateStr, isRecurringType, isNonWorkingDayFor, SCHEDULER_TZ } from "./recurrence";
import { isBoss, scopeTasks } from "./scope";
import { logger } from "./logger";
import { createNotifications } from "./webPush";

// ── Auto-generate recurring task occurrences ───────────────────
// Every daily/weekly/monthly task is recurring. Each chain has a single
// "head" (the latest occurrence — no other task points to it via
// parentTaskId). Once per period we clone the head into a fresh pending
// occurrence dated today, preserving history. `lastRunDate` (a period
// key) guards against generating the same period twice.
// Maps the task `type` to the capitalized frequency the due-date parser expects.
const TYPE_TO_FREQ: Record<string, string> = {
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
  quarterly: "Quarterly",
  annual: "Annual",
};

// Clone a chain head into a fresh pending occurrence for the current period.
// Returns true when a new row was actually inserted (false = the
// (parent_task_id, last_run_date) guard already had this period).
// `autoGenerated: false` marks occurrences a user explicitly requested via
// "Generate Today's Tasks" so the weekend boot-cleanup never removes them.
async function cloneRecurringHead(
  head: typeof tasksTable.$inferSelect,
  cur: string,
  opts: { autoGenerated: boolean },
): Promise<number | null> {
  // Recurring tasks carrying a due-date rule recompute the occurrence's due
  // date for the new period (e.g. "6th of next month" -> the 6th this month);
  // ad-hoc recurring tasks keep defaulting to the generation day.
  let due = istDateStr();
  if (head.dueRule) {
    const computed = computeDueDate(
      { dueDateText: head.dueRule, frequency: TYPE_TO_FREQ[head.type] ?? "Monthly" },
      istToday(),
    );
    if (computed) due = ymd(computed);
  }

  const inserted = await db
    .insert(tasksTable)
    .values({
      title: head.title,
      description: head.description,
      assignedTo: head.assignedTo,
      assignedBy: head.assignedBy,
      dueDate: due,
      dueRule: head.dueRule,
      priority: head.priority,
      status: "pending",
      type: head.type,
      category: head.category,
      department: head.department,
      // Each new occurrence starts with a FRESH remark — yesterday's remark
      // belongs to yesterday's task (user request, July 2026).
      remark: null,
      parentTaskId: head.id,
      autoGenerated: opts.autoGenerated,
      lastRunDate: cur,
    })
    .onConflictDoNothing({
      target: [tasksTable.parentTaskId, tasksTable.lastRunDate],
      where: sql`parent_task_id IS NOT NULL`,
    })
    .returning({ id: tasksTable.id });
  return inserted.length > 0 ? inserted[0].id : null;
}

export async function generateRecurringTasks(): Promise<number> {
  logger.info("Running recurring task generation job");
  const all = await db.select().from(tasksTable);
  const hasChild = new Set<number>();
  for (const t of all) if (t.parentTaskId != null) hasChild.add(t.parentTaskId);

  const users = await db.select().from(usersTable);
  const userById = new Map(users.map((u) => [u.id, u]));
  const optedOut = optedOutIds(users);

  const today = istDateStr();
  let created = 0;
  // Per-user tally of freshly generated DAILY occurrences so we can push one
  // "your daily tasks are ready" notification per person (not one per task).
  const dailyByUser = new Map<number, { count: number; taskId: number }>();

  for (const head of all) {
    if (head.complianceItemId != null) continue; // compliance tasks recur via generateComplianceTasks
    if (!isRecurringType(head.type)) continue;
    if (head.assignedTo != null && optedOut.has(head.assignedTo)) continue; // opted-out user
    if (hasChild.has(head.id)) continue; // not the latest occurrence in its chain
    const cur = periodKey(head.type);

    // Initialize an un-tracked head without generating a duplicate this period.
    if (!head.lastRunDate) {
      await db.update(tasksTable).set({ lastRunDate: cur }).where(eq(tasksTable.id, head.id));
      continue;
    }
    if (cur <= head.lastRunDate) continue; // current period already generated

    // Weekend policy: DAILY occurrences are skipped on the assignee's
    // non-working day (Sunday for everyone / 1st Saturday for everyone /
    // other Saturdays for Head Office non-MIS). lastRunDate is left
    // untouched, so the next working day generates normally. Someone who IS
    // working can self-serve via "Generate Today's Tasks" (see
    // generateMyDailyTasks). Weekly/monthly/etc. still generate — they span
    // the whole period, not a single day.
    if (head.type === "daily") {
      const assignee = head.assignedTo != null ? userById.get(head.assignedTo) : undefined;
      if (isNonWorkingDayFor(assignee, today)) continue;
    }

    const newId = await cloneRecurringHead(head, cur, { autoGenerated: true });
    if (newId != null) {
      created++;
      if (head.type === "daily" && head.assignedTo != null) {
        const prev = dailyByUser.get(head.assignedTo);
        if (prev) prev.count++;
        else dailyByUser.set(head.assignedTo, { count: 1, taskId: newId });
      }
    }
  }

  // One in-app + push notification per user whose daily tasks were generated.
  // Guarded by the same once-per-day claim lock as the digest jobs: generation
  // itself is idempotent (onConflictDoNothing), but concurrent runs (boot +
  // cron, or two instances) could each create disjoint subsets and each try to
  // notify — the claim makes the notification at-most-once per IST day.
  if (dailyByUser.size > 0 && (await claimScheduledJob("daily-task-notify", today))) {
    try {
      await createNotifications(
        [...dailyByUser.entries()].map(([userId, { count, taskId }]) => ({
          userId,
          type: "daily_tasks",
          message:
            count === 1
              ? "Your daily task for today has been generated. Please check your task list."
              : `Your ${count} daily tasks for today have been generated. Please check your task list.`,
          taskId,
        })),
      );
    } catch (err) {
      await releaseScheduledJob("daily-task-notify", today).catch(() => {});
      throw err;
    }
  }

  logger.info({ created }, "Recurring task generation complete");
  return created;
}

// Self-serve generation for someone who IS working on an off day (Sunday /
// 1st Saturday): clone TODAY's occurrence of every daily chain assigned to
// this user, ignoring the weekend skip. Idempotent — the same period-key +
// unique-index guards apply, so clicking twice creates nothing extra. Only
// the caller's own daily tasks are touched.
export async function generateMyDailyTasks(userId: number): Promise<number> {
  if (NO_AUTO_TASKS_USER_IDS.has(userId)) return 0; // opted-out (code baseline)
  const [me] = await db.select({ autoTasksEnabled: usersTable.autoTasksEnabled }).from(usersTable).where(eq(usersTable.id, userId));
  if (me && !me.autoTasksEnabled) return 0; // opted-out (admin toggle)
  const all = await db.select().from(tasksTable);
  const hasChild = new Set<number>();
  for (const t of all) if (t.parentTaskId != null) hasChild.add(t.parentTaskId);

  const cur = periodKey("daily");
  let created = 0;

  for (const head of all) {
    if (head.assignedTo !== userId) continue;
    if (head.type !== "daily") continue;
    if (head.complianceItemId != null) continue;
    if (hasChild.has(head.id)) continue;

    // Untracked head: initialize it as today's occurrence (same as the
    // scheduled job would).
    if (!head.lastRunDate) {
      await db.update(tasksTable).set({ lastRunDate: cur }).where(eq(tasksTable.id, head.id));
      continue;
    }
    if (cur <= head.lastRunDate) continue; // today's occurrence already exists

    if ((await cloneRecurringHead(head, cur, { autoGenerated: false })) != null) created++;
  }

  logger.info({ userId, created }, "Self-serve daily task generation complete");
  return created;
}

// ── Auto-generate compliance task occurrences ──────────────────
// Mirror every active Compliance Calendar activity into a real task for the
// current period so the Accounts team can see and complete it in All Tasks. One
// task per item per period (idempotent via the (compliance_item_id, last_run_date)
// unique index). The task's initial status is derived from the existing
// per-company compliance grid so the two views agree from the moment it appears.
// Compliance frequencies map onto the task `type` so the All Tasks row shows the
// real cadence (Monthly/Quarterly/Annual…) instead of "One Time". Unknown values
// fall back to one_time. The recurring generator skips compliance-linked tasks
// (see generateRecurringTasks) so these types never trigger double-generation.
const COMPLIANCE_FREQ_TO_TASK_TYPE: Record<string, string> = {
  daily: "daily",
  weekly: "weekly",
  monthly: "monthly",
  quarterly: "quarterly",
  annual: "annual",
};

export async function generateComplianceTasks(): Promise<number> {
  logger.info("Running compliance task generation job");
  const items = await db.select().from(complianceItemsTable).where(eq(complianceItemsTable.active, true));
  if (!items.length) {
    logger.info({ created: 0 }, "Compliance task generation complete");
    return 0;
  }

  // Only companies still on the active master list have a tickable cell in the
  // Compliance Calendar, so initial task completion must consider exactly those
  // (mirrors Compliance.tsx + complianceSync).
  const activeCompanyRows = await db
    .select({ name: complianceCompaniesTable.name })
    .from(complianceCompaniesTable)
    .where(eq(complianceCompaniesTable.active, true));
  const activeCompanies = new Set(activeCompanyRows.map((r) => r.name));

  // Pre-index every "done" status so initial task state is computed without an
  // extra query per item.
  const statuses = await db.select().from(complianceStatusTable);
  const doneByItemPeriod = new Map<string, Set<string>>();
  for (const s of statuses) {
    if (!s.done) continue;
    const key = `${s.itemId}|${s.periodKey}`;
    let set = doneByItemPeriod.get(key);
    if (!set) {
      set = new Set<string>();
      doneByItemPeriod.set(key, set);
    }
    set.add(s.company);
  }

  const today = istToday();
  let created = 0;

  for (const item of items) {
    const applicable = item.companies.length
      ? item.companies.filter((c) => activeCompanies.has(c))
      : ["ALL"];
    const due = computeDueDate({ dueDateText: item.dueDateText, frequency: item.frequency }, today);
    const taskType = COMPLIANCE_FREQ_TO_TASK_TYPE[(item.frequency ?? "").trim().toLowerCase()] ?? "one_time";
    const pKey = periodKeyForDate(item.frequency, due ?? today);
    const doneCompanies = doneByItemPeriod.get(`${item.id}|${pKey}`) ?? new Set<string>();
    const allDone = applicable.every((c) => doneCompanies.has(c));

    const descParts = [
      item.activity?.trim() || null,
      item.companies.length ? `Companies: ${item.companies.join(", ")}` : null,
    ].filter(Boolean);

    const inserted = await db
      .insert(tasksTable)
      .values({
        title: item.compliance,
        description: descParts.length ? descParts.join(" — ") : null,
        assignedTo: item.assignedTo,
        assignedBy: null,
        dueDate: due ? ymd(due) : null,
        priority: "medium",
        status: allDone ? "done" : "pending",
        // Reflect the compliance cadence in the task type so the row shows the real
        // frequency. Double-generation is prevented in generateRecurringTasks, which
        // skips any compliance-linked task regardless of type.
        type: taskType,
        category: "Compliance",
        department: "Accounts",
        complianceItemId: item.id,
        autoGenerated: true,
        lastRunDate: pKey,
      })
      .onConflictDoNothing({
        target: [tasksTable.complianceItemId, tasksTable.lastRunDate],
        where: sql`compliance_item_id IS NOT NULL`,
      })
      .returning({ id: tasksTable.id });
    if (inserted.length) created++;
  }

  logger.info({ created }, "Compliance task generation complete");
  return created;
}

// ── Once-per-day claim lock ────────────────────────────────────
// The 9 AM digest/dashboard jobs can be fired from TWO places: the in-app cron
// (only reliable when the Autoscale app is awake) and a separate Replit
// Scheduled Deployment (which is why they exist as a standalone entry). To make
// sure each email is sent AT MOST once per day regardless of which one fires
// first, both go through this atomic claim: an INSERT ... ON CONFLICT DO NOTHING
// on the shared app_settings table keyed by (job, IST date). Whoever inserts the
// row first "owns" the run; the loser sees 0 rows and skips. Manual admin
// triggers (POST /email/send-*-now) bypass this on purpose so a Boss/MIS can
// always force a resend.
function jobLockKey(jobKey: string, dateStr: string): string {
  return `emailrun:${jobKey}:${dateStr}`;
}

async function claimScheduledJob(jobKey: string, dateStr: string): Promise<boolean> {
  const rows = await db
    .insert(appSettingsTable)
    .values({ key: jobLockKey(jobKey, dateStr), value: new Date().toISOString() })
    .onConflictDoNothing({ target: appSettingsTable.key })
    .returning({ key: appSettingsTable.key });
  return rows.length === 1;
}

// Release a claim so the day can be retried. Called when the send THROWS, so a
// crash/DB error after claiming but before delivering does not permanently
// suppress that day's emails (a later trigger — in-app cron, scheduled job, or
// the /api/cron endpoint — can retry). A hard process kill mid-send is the one
// residual edge; the Boss/MIS manual "send now" buttons bypass the lock entirely
// and cover that case.
async function releaseScheduledJob(jobKey: string, dateStr: string): Promise<void> {
  await db.delete(appSettingsTable).where(eq(appSettingsTable.key, jobLockKey(jobKey, dateStr)));
}

// Run a claimed job, releasing the claim if it throws so today can be retried.
async function runClaimedJob<T>(jobKey: string, run: () => Promise<T>): Promise<T | null> {
  const dateStr = istDateStr();
  if (!(await claimScheduledJob(jobKey, dateStr))) {
    logger.info({ jobKey }, "Job already claimed for today — skipping to avoid a duplicate send");
    return null;
  }
  try {
    return await run();
  } catch (err) {
    await releaseScheduledJob(jobKey, dateStr).catch(() => {});
    throw err;
  }
}

export async function runDailyDigestOnce(): Promise<Awaited<ReturnType<typeof sendDailyDigest>> | null> {
  return runClaimedJob("daily-digest", sendDailyDigest);
}

export async function runDashboardDigestOnce(): Promise<Awaited<ReturnType<typeof sendDashboardDigest>> | null> {
  return runClaimedJob("dashboard-digest", sendDashboardDigest);
}

// ── Fun lunch reminders (in-app only — NOT tasks, NO email) ────
// Two light-hearted daily nudges for EVERYONE via the in-app bell. These
// replace the old "Order your lunch"/"Go for lunch" entries that used to
// clutter the task list. Fired by the in-app cron when the Autoscale app is
// awake and by GET/POST /api/cron/lunch-reminder (external scheduler) otherwise;
// the once-per-day claim lock makes each at-most-once per day no matter which
// trigger fires first.
const LUNCH_REMINDERS = {
  order: { job: "lunch-order", message: "🍱 Time to order your lunch — please place your order by 12:00 PM!" },
  eat: { job: "lunch-eat", message: "🥗 It's 1:00 PM — lunch break time. Step away and enjoy your meal!" },
} as const;
export type LunchReminderKind = keyof typeof LUNCH_REMINDERS;

export function isLunchReminderKind(v: unknown): v is LunchReminderKind {
  return v === "order" || v === "eat";
}

// Titles of the retired joke "lunch" tasks — deleted on boot (see startScheduler)
// so they stop showing in the task list / digest and stop recurring. They now
// live as this in-app reminder + a dashboard banner instead.
const RETIRED_LUNCH_TITLES = ["Order your lunch at 12:00 PM", "Go for lunch at 1:00 PM"];

export async function sendLunchReminder(kind: LunchReminderKind): Promise<{ notified: number }> {
  const { message } = LUNCH_REMINDERS[kind];
  const recipients = await db
    .select({ id: usersTable.id })
    .from(usersTable)
    .where(and(eq(usersTable.status, "Active"), isNotNull(usersTable.username)));
  if (!recipients.length) return { notified: 0 };
  await createNotifications(
    recipients.map((u) => ({ userId: u.id, type: "lunch_reminder", message }))
  );
  logger.info({ kind, notified: recipients.length }, "Lunch reminder sent");
  return { notified: recipients.length };
}

export async function runLunchReminderOnce(
  kind: LunchReminderKind,
): Promise<{ notified: number } | null> {
  return runClaimedJob(LUNCH_REMINDERS[kind].job, () => sendLunchReminder(kind));
}

// One-time retirement of the old joke "lunch" tasks. Idempotent: after they are
// gone this deletes nothing. Scoped tightly (exact titles + no explicit
// assigner) so it only removes those routine entries, and runs before the boot
// recurring generation so they are not re-cloned.
async function retireLunchTasks(): Promise<void> {
  const removed = await db
    .delete(tasksTable)
    .where(and(inArray(tasksTable.title, RETIRED_LUNCH_TITLES), isNull(tasksTable.assignedBy)))
    .returning({ id: tasksTable.id });
  if (removed.length) logger.info({ removed: removed.length }, "Retired old lunch tasks");
}

// One-time cleanup (user request, July 2026): remove every Thane Center task
// created before 1 July 2026, plus its notifications/transfer records.
// Idempotent — once those rows are gone this deletes nothing. Runs before the
// boot recurring generation so dead chains are not re-cloned.
async function cleanupThanePreJulyTasks(): Promise<void> {
  const cutoff = new Date("2026-07-01T00:00:00+05:30");
  const thaneUsers = await db
    .select({ id: usersTable.id })
    .from(usersTable)
    .where(eq(usersTable.center, "Thane Center"));
  const userIds = thaneUsers.map((u) => u.id);
  if (!userIds.length) return;

  const doomed = await db
    .select({ id: tasksTable.id })
    .from(tasksTable)
    .where(and(inArray(tasksTable.assignedTo, userIds), lt(tasksTable.createdAt, cutoff)));
  const taskIds = doomed.map((t) => t.id);
  if (!taskIds.length) return;

  await db.delete(notificationsTable).where(inArray(notificationsTable.taskId, taskIds));
  await db.delete(taskTransfersTable).where(inArray(taskTransfersTable.taskId, taskIds));
  const removed = await db
    .delete(tasksTable)
    .where(inArray(tasksTable.id, taskIds))
    .returning({ id: tasksTable.id });
  logger.info({ removed: removed.length }, "Cleaned up pre-July Thane Center tasks");
}

// Boot cleanup: opted-out users (NO_AUTO_TASKS_USER_IDS) must have NO tasks at
// all. Deleting on boot keeps them permanently empty and — because production
// has a separate DB the agent can't touch directly — cleans prod on the first
// boot after republish. Idempotent: once empty this deletes nothing.
async function cleanupOptedOutUserTasks(): Promise<void> {
  const users = await db
    .select({ id: usersTable.id, autoTasksEnabled: usersTable.autoTasksEnabled })
    .from(usersTable);
  const userIds = [...optedOutIds(users)];
  if (!userIds.length) return;
  const doomed = await db
    .select({ id: tasksTable.id })
    .from(tasksTable)
    .where(inArray(tasksTable.assignedTo, userIds));
  const taskIds = doomed.map((t) => t.id);
  if (!taskIds.length) return;
  await db.delete(notificationsTable).where(inArray(notificationsTable.taskId, taskIds));
  await db.delete(taskTransfersTable).where(inArray(taskTransfersTable.taskId, taskIds));
  const removed = await db
    .delete(tasksTable)
    .where(inArray(tasksTable.id, taskIds))
    .returning({ id: tasksTable.id });
  logger.info({ removed: removed.length }, "Cleaned up opted-out users' tasks");
}

// One-time seed (July 2026): the Thane pre-July cleanup above also wiped
// Thane's 4 weekly "Team Leader KRA" templates, so weekly generation silently
// stopped for Thane only. Recreate them for Thane's Center Head + Team Leaders
// by copying Navi Mumbai's weekly templates. Idempotent — skips any (user,
// title) that already has a weekly task. lastRunDate is set to the PREVIOUS
// week's key so the boot generation right after this immediately creates the
// current week's occurrences. Runs in every environment (dev already seeded →
// no-op; production seeds on first boot after publish).
// Advisory-lock key so concurrent server instances (autoscale boots) cannot
// both run the seed's check-then-insert and create duplicate recurring roots
// (duplicate roots each become a chain head → weekly tasks double forever).
const THANE_WEEKLY_SEED_LOCK = 723_001;

// Users who must NEVER get auto-generated recurring tasks (weekly seed above
// AND the daily/weekly/monthly generator). This CODE baseline is a durable
// floor that survives checkpoint/rollback (DB flags proved non-durable in dev).
// User 9 (Edwin Thomas, Thane Center Head): opted out on request, July 2026.
// On top of this baseline, Boss/MIS can opt anyone out from the app via the
// per-user `autoTasksEnabled` flag (Access Control page) — see optedOutIds().
const NO_AUTO_TASKS_USER_IDS = new Set<number>([9]);

// The full opted-out set = the code baseline UNION every user whose
// `autoTasksEnabled` flag is false. Pass the already-loaded user rows to avoid
// a second query; callers that don't have them can load first.
function optedOutIds(users: { id: number; autoTasksEnabled: boolean }[]): Set<number> {
  const set = new Set<number>(NO_AUTO_TASKS_USER_IDS);
  for (const u of users) if (!u.autoTasksEnabled) set.add(u.id);
  return set;
}

async function ensureThaneWeeklyTemplates(): Promise<void> {
  await db.transaction(async (tx) => {
    // Serializes concurrent seeders; lock releases at transaction end.
    await tx.execute(sql`SELECT pg_advisory_xact_lock(${THANE_WEEKLY_SEED_LOCK})`);

    const targets = (
      await tx
        .select({ id: usersTable.id, autoTasksEnabled: usersTable.autoTasksEnabled })
        .from(usersTable)
        .where(
          and(eq(usersTable.center, "Thane Center"), inArray(usersTable.role, ["Center Head", "Team Leader"])),
        )
    ).filter((u) => !NO_AUTO_TASKS_USER_IDS.has(u.id) && u.autoTasksEnabled);
    if (!targets.length) return;

    // Source: Navi Mumbai's weekly root templates, one row per distinct title.
    const sourceRows = await tx
      .select({
        title: tasksTable.title,
        description: tasksTable.description,
        priority: tasksTable.priority,
        category: tasksTable.category,
        department: tasksTable.department,
      })
      .from(tasksTable)
      .innerJoin(usersTable, eq(usersTable.id, tasksTable.assignedTo))
      .where(
        and(
          eq(usersTable.center, "Navi Mumbai Center"),
          eq(tasksTable.type, "weekly"),
          isNull(tasksTable.parentTaskId),
          isNull(tasksTable.dueDate),
        ),
      );
    const templates = new Map<string, (typeof sourceRows)[number]>();
    for (const r of sourceRows) if (!templates.has(r.title)) templates.set(r.title, r);
    if (!templates.size) return;

    // Existence check is deliberately BROAD (any weekly task for that user +
    // title, template or occurrence): if occurrences exist the chain is alive
    // (generation clones whatever head has no child, even with a dangling
    // parentTaskId), so adding a new root would create a SECOND chain and
    // double-generate. Only seed when the user has nothing for that title.
    const targetIds = targets.map((u) => u.id);
    const existing = await tx
      .select({ assignedTo: tasksTable.assignedTo, title: tasksTable.title })
      .from(tasksTable)
      .where(and(inArray(tasksTable.assignedTo, targetIds), eq(tasksTable.type, "weekly")));
    const have = new Set(existing.map((t) => `${t.assignedTo}|${t.title}`));

    // Previous week's period key (Monday of last week) so generation fires now.
    const prevWeek = periodKey("weekly", new Date(Date.now() - 7 * 24 * 60 * 60 * 1000));

    const rows: (typeof tasksTable.$inferInsert)[] = [];
    for (const u of targets) {
      for (const tp of templates.values()) {
        if (have.has(`${u.id}|${tp.title}`)) continue;
        rows.push({
          title: tp.title,
          description: tp.description,
          assignedTo: u.id,
          assignedBy: null,
          priority: tp.priority,
          status: "pending",
          type: "weekly",
          category: tp.category,
          department: tp.department,
          autoGenerated: false,
          lastRunDate: prevWeek,
        });
      }
    }
    if (!rows.length) return;
    await tx.insert(tasksTable).values(rows);
    logger.info({ seeded: rows.length }, "Seeded missing Thane weekly templates");
  });
}

// ── Sonali (Accounts) JD task seed (July 2026) ─────────────────
// The user provided Sonali Pawar's full accounts JD sheet (Monthly fixed /
// Daily / month-end Audit Reports per company). Prod DB is read-only to the
// agent, so — like the Thane weekly seed — this ships as an idempotent boot
// seed: it inserts each missing head task (matched by exact title) for the
// user looked up by username. Each seed row is its OWN first occurrence
// (dueDate = next upcoming date from its rule, lastRunDate = that date's
// period key), so the generator clones only from the NEXT period onward.
// GSTR-1 / GSTR-3B rows from the sheet are intentionally omitted — they
// already exist as "GST – GSTR-1 (Monthly)" / "GST – GSTR-3B (Monthly)".
const SONALI_JD_SEED_LOCK = 723_002;
const SONALI_USERNAME = "sonali.pawar";

type JdSeedItem = { title: string; type: "daily" | "monthly" | "quarterly"; dueRule: string | null };

function jd(
  type: JdSeedItem["type"],
  dueRule: string | null,
  base: string,
  companies: string[],
): JdSeedItem[] {
  return companies.map((c) => ({ title: `${base} — ${c}`, type, dueRule }));
}

const INFINITY_CENTERS = ["Infinity - Thane", "Infinity - Pune", "Infinity - Malad", "Infinity - Navi Mumbai"];

const SONALI_JD_TASKS: JdSeedItem[] = [
  // Monthly fixed
  ...jd("monthly", "1st of every month", "Mails for Invoice & Petty Cash", INFINITY_CENTERS),
  ...jd("monthly", "3rd of every month", "Salary booking", ["Parabolic"]),
  ...jd("monthly", "5th of every month", "Salary booking", INFINITY_CENTERS),
  ...jd("monthly", "5th of every month", "All Vendor Invoice Booking", ["Parabolic", ...INFINITY_CENTERS, "Iken", "Woncore"]),
  ...jd("monthly", "6th of every month", "TDS Preparation", ["Parabolic", ...INFINITY_CENTERS, "Iken", "Woncore"]),
  ...jd("monthly", "9th of every month", "Petty Cash booking", INFINITY_CENTERS),
  ...jd("monthly", "9th of every month", "CC Exp Booking", ["Parabolic", ...INFINITY_CENTERS, "Infinity - HO"]),
  ...jd("monthly", "9th of every month", "Sales Booking - Excel Sheet", ["Infinity"]),
  ...jd("monthly", "9th of every month", "Sales Booking", ["Parabolic"]),
  ...jd("monthly", "11th of every month", "P&L Preparation", ["Infinity"]),
  ...jd("monthly", "12th of every month", "P&L Preparation", ["Parabolic"]),
  ...jd("monthly", "25th of every month", "Incentive Preparation", INFINITY_CENTERS),
  ...jd("quarterly", "Quarter end", "TDS Return - 26Q", ["Infinity", "Parabolic", "Iken", "Woncore"]),
  ...jd("quarterly", "Quarter end", "TDS Return - 24Q", ["Infinity", "Parabolic"]),
  // Daily
  ...jd("daily", "Daily", "Bank Updation", ["Infinity", "Parabolic", "Iken", "EI", "PRBLC PTE", "Woncore"]),
  ...jd("daily", "Daily", "Payments", ["Infinity", "Parabolic", "Woncore"]),
  ...jd("daily", "Daily", "Cash Offer - Weekly/fortnightly/Monthly", ["Infinity"]),
  // Audit Reports (month end)
  ...jd("monthly", "Month end", "Salary Reconciliation", ["Infinity", "Parabolic"]),
  ...jd("monthly", "Month end", "PT Reconciliation", ["Infinity", "Parabolic"]),
  ...jd("monthly", "Month end", "PF Reconciliation", ["Infinity", "Parabolic"]),
  ...jd("monthly", "Month end", "ESIC Reconciliation", ["Infinity", "Parabolic"]),
  ...jd("monthly", "Month end", "GST Reconciliation", ["Infinity", "Parabolic", "Iken"]),
  ...jd("monthly", "Month end", "Bank Reconciliation (Month End)", ["Infinity", "Parabolic"]),
  ...jd("monthly", "Month end", "TDS Reconciliation", ["Infinity", "Parabolic", "Iken"]),
  ...jd("monthly", "Month end", "Company Annual Compliances", ["Infinity", "Parabolic"]),
  ...jd("quarterly", "Quarter end", "TDS Filling Quarterly", ["Infinity", "Parabolic", "Woncore", "Iken"]),
  ...jd("monthly", "Month end", "Maintained Vendor Sheet", ["Infinity"]),
  ...jd("monthly", "Month end", "Employee Loan Sheet", ["Infinity"]),
  ...jd("monthly", "Month end", "Interest on Loan Sheet", ["Infinity", "Parabolic", "Woncore"]),
  ...jd("monthly", "Month end", "Cash Offers Sheet", ["Infinity"]),
];

// Next upcoming due date for a seed item (never in the past, so the seeded
// first occurrence isn't born overdue) + the matching period key. Daily seeds
// advance to the user's next WORKING day so a Sunday/off-Saturday boot never
// plants an off-day daily task (seed rows are autoGenerated=false, so the
// weekend boot-cleanup would not remove them).
function jdSeedDue(
  item: JdSeedItem,
  user: { center: string | null; department: string | null },
): { due: string; period: string } {
  const today = istToday();
  const freq = TYPE_TO_FREQ[item.type] ?? "Monthly";
  let due: Date | null = null;
  if (item.type === "daily") {
    const d = new Date(today);
    while (isNonWorkingDayFor(user, ymd(d))) d.setDate(d.getDate() + 1);
    due = d;
  } else if (item.dueRule) {
    due = computeDueDate({ dueDateText: item.dueRule, frequency: freq }, today);
  }
  if (!due || ymd(due) < ymd(today)) {
    if (item.type === "monthly" && item.dueRule) {
      const firstOfNext = new Date(today.getFullYear(), today.getMonth() + 1, 1);
      due = computeDueDate({ dueDateText: item.dueRule, frequency: freq }, firstOfNext) ?? firstOfNext;
    } else {
      due = today;
    }
  }
  return { due: ymd(due), period: periodKey(item.type, due) };
}

async function ensureSonaliJdTasks(): Promise<void> {
  await db.transaction(async (tx) => {
    await tx.execute(sql`SELECT pg_advisory_xact_lock(${SONALI_JD_SEED_LOCK})`);

    const [user] = await tx
      .select({
        id: usersTable.id,
        autoTasksEnabled: usersTable.autoTasksEnabled,
        center: usersTable.center,
        department: usersTable.department,
      })
      .from(usersTable)
      .where(eq(usersTable.username, SONALI_USERNAME));
    if (!user || NO_AUTO_TASKS_USER_IDS.has(user.id) || !user.autoTasksEnabled) return;

    // Broad existence check (any task with that exact title, template or
    // occurrence) — same reasoning as the Thane seed: a live chain must never
    // get a second root or it double-generates.
    const existing = await tx
      .select({ title: tasksTable.title })
      .from(tasksTable)
      .where(eq(tasksTable.assignedTo, user.id));
    const have = new Set(existing.map((t) => t.title));

    const rows: (typeof tasksTable.$inferInsert)[] = [];
    for (const item of SONALI_JD_TASKS) {
      if (have.has(item.title)) continue;
      const { due, period } = jdSeedDue(item, user);
      rows.push({
        title: item.title,
        assignedTo: user.id,
        assignedBy: null,
        priority: "medium",
        status: "pending",
        type: item.type,
        category: "Compliance",
        department: "Accounts",
        dueDate: due,
        dueRule: item.dueRule,
        autoGenerated: false,
        lastRunDate: period,
      });
    }
    if (!rows.length) return;
    await tx.insert(tasksTable).values(rows);
    logger.info({ seeded: rows.length }, "Seeded missing Sonali JD tasks");
  });
}

// Boot cleanup (July 2026 weekend policy): remove auto-generated DAILY
// occurrences that were created on a non-working day for their assignee
// (any Sunday, any 1st Saturday, Head Office non-MIS Saturdays) — these
// existed before the weekend skip was added and clutter the list as fake
// overdue work. Only pending, auto-generated, non-compliance occurrences are
// touched: anything marked done stays (the person actually worked that day),
// and self-serve occurrences (autoGenerated=false via "Generate Today's
// Tasks") always stay. Children are re-parented to the doomed row's own
// parent so recurrence chains stay intact; processed newest-first so a
// doomed child is re-linked before its (also doomed) parent goes away.
// Idempotent + generic — safe to run on every boot.
async function cleanupNonWorkingDayDailyTasks(): Promise<void> {
  const users = await db.select().from(usersTable);
  const userById = new Map(users.map((u) => [u.id, u]));

  const rows = await db
    .select()
    .from(tasksTable)
    .where(
      and(
        eq(tasksTable.type, "daily"),
        eq(tasksTable.autoGenerated, true),
        eq(tasksTable.status, "pending"),
        isNull(tasksTable.complianceItemId),
        isNotNull(tasksTable.parentTaskId),
        isNotNull(tasksTable.lastRunDate),
      ),
    );

  const doomed = rows
    .filter(
      (t) =>
        /^\d{4}-\d{2}-\d{2}$/.test(t.lastRunDate!) &&
        isNonWorkingDayFor(t.assignedTo != null ? userById.get(t.assignedTo) : undefined, t.lastRunDate!),
    )
    .sort((a, b) => (a.lastRunDate! < b.lastRunDate! ? 1 : -1)); // newest first

  if (!doomed.length) return;

  for (const t of doomed) {
    // Keep the chain linked: children point to this row's own parent instead.
    await db
      .update(tasksTable)
      .set({ parentTaskId: t.parentTaskId })
      .where(eq(tasksTable.parentTaskId, t.id));
    await db.delete(notificationsTable).where(eq(notificationsTable.taskId, t.id));
    await db.delete(taskTransfersTable).where(eq(taskTransfersTable.taskId, t.id));
    await db.delete(tasksTable).where(eq(tasksTable.id, t.id));
  }
  logger.info({ removed: doomed.length }, "Cleaned up daily tasks generated on non-working days");
}

// ── Daily digest ───────────────────────────────────────────────
// One combined email per user listing the tasks relevant for today:
// everything still open that is due today or overdue.
export async function sendDailyDigest(): Promise<{ sent: number; eligible: number; skippedNoEmail: number; failedSend: number }> {
  logger.info("Running daily digest job");
  const today = istDateStr();
  const users = await db.select().from(usersTable);
  let sent = 0;
  let eligible = 0;
  let skippedNoEmail = 0;
  let failedSend = 0;

  for (const user of users) {
    const tasks = await db
      .select()
      .from(tasksTable)
      .where(and(eq(tasksTable.assignedTo, user.id), ne(tasksTable.status, "done")));

    const relevant = tasks.filter((t) => t.dueDate && t.dueDate <= today);
    if (!relevant.length) continue;

    // This user has tasks worth a reminder, but can only receive one if they
    // have an email address on file.
    eligible++;
    if (!user.email) { skippedNoEmail++; continue; }

    const ok = await sendDailyDigestEmail({
      toEmail: user.email,
      toName: user.name,
      dateStr: today,
      tasks: relevant
        .map((t) => ({
          title: t.title,
          status: t.status,
          priority: t.priority,
          type: t.type,
          dueDate: t.dueDate,
          overdue: !!t.dueDate && t.dueDate < today,
        }))
        .sort((a, b) => Number(b.overdue) - Number(a.overdue)),
    });
    if (ok) sent++;
    else failedSend++;

    // Pace sends to stay under Resend's 2 requests/second limit.
    await new Promise((r) => setTimeout(r, 600));
  }

  logger.info({ sent, eligible, skippedNoEmail, failedSend }, "Daily digest complete");
  return { sent, eligible, skippedNoEmail, failedSend };
}

// ── Daily dashboard summary ────────────────────────────────────
// A morning snapshot of the live Dashboard (KPI cards + by-category /
// by-team-member breakdowns) emailed to a fixed set of people. Each recipient's
// numbers are scoped to exactly what they're entitled to see on the Dashboard
// page (Boss/MIS get everything; others get their own team), via scopeTasks.
// Keyed by stable user id (not name) so duplicate names can never misroute a
// summary to the wrong person/email.
const DASHBOARD_RECIPIENT_IDS = [
  6, // Vikas Gupta (MIS)
  9, // Edwin Thomas (Center Head, Thane)
  13, // Prakash Thakur (Team Leader, Thane)
  14, // Riyaz Khan (Team Leader, Thane)
  15, // Swapnil Reddy (Team Leader, Thane)
  16, // Sujit Yadav (Team Leader, Thane)
];

export async function sendDashboardDigest(): Promise<{ sent: number; eligible: number; skippedNoEmail: number; failedSend: number }> {
  logger.info("Running daily dashboard summary job");
  const today = istDateStr();
  const users = await db.select().from(usersTable);
  const allTasks = await db.select().from(tasksTable);
  let sent = 0;
  let eligible = 0;
  let skippedNoEmail = 0;
  let failedSend = 0;

  for (const id of DASHBOARD_RECIPIENT_IDS) {
    const recipient = users.find((u) => u.id === id);
    if (!recipient) {
      logger.warn({ id }, "Dashboard recipient not found");
      continue;
    }
    eligible++;
    if (!recipient.email) { skippedNoEmail++; continue; }

    const scoped = scopeTasks(recipient, users, allTasks);
    const total = scoped.length;
    const pending = scoped.filter((t) => t.status === "pending").length;
    const inProgress = scoped.filter((t) => t.status === "inProgress").length;
    const done = scoped.filter((t) => t.status === "done").length;
    const completionRate = total > 0 ? Math.round((done / total) * 100) : 0;

    const catMap = new Map<string, { count: number; done: number }>();
    for (const t of scoped) {
      const cat = t.category ?? "Uncategorized";
      if (!catMap.has(cat)) catMap.set(cat, { count: 0, done: 0 });
      const e = catMap.get(cat)!;
      e.count++;
      if (t.status === "done") e.done++;
    }

    const userMap = new Map<number, { name: string; department: string; total: number; done: number; pending: number }>();
    for (const u of users) userMap.set(u.id, { name: u.name, department: u.department, total: 0, done: 0, pending: 0 });
    for (const t of scoped) {
      if (!t.assignedTo) continue;
      const e = userMap.get(t.assignedTo);
      if (!e) continue;
      e.total++;
      if (t.status === "done") e.done++;
      else e.pending++;
    }

    const ok = await sendDashboardEmail({
      toEmail: recipient.email,
      toName: recipient.name,
      dateStr: today,
      total,
      pending,
      inProgress,
      done,
      completionRate,
      byCategory: Array.from(catMap.entries()).map(([category, v]) => ({ category, ...v })),
      byUser: Array.from(userMap.values()).filter((v) => v.total > 0),
    });
    if (ok) sent++;
    else failedSend++;

    // Pace sends to stay under Resend's 2 requests/second limit.
    await new Promise((r) => setTimeout(r, 600));
  }

  logger.info({ sent, eligible, skippedNoEmail, failedSend }, "Daily dashboard summary complete");
  return { sent, eligible, skippedNoEmail, failedSend };
}

// Calendar arithmetic on a "YYYY-MM-DD" string, timezone-safe (pure UTC math).
function addDaysStr(dateStr: string, delta: number): string {
  const [y, m, d] = dateStr.split("-").map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d));
  dt.setUTCDate(dt.getUTCDate() + delta);
  return dt.toISOString().slice(0, 10);
}

// The day a due-date reminder should fire: two working (non-holiday) days
// before the due date, landing on a non-holiday day. A holiday inside the lead
// window moves the reminder earlier so it always arrives BEFORE the holiday —
// important for Accounts (payment / report) tasks whose due date can't slip.
function reminderDateFor(dueDate: string, holidaySet: Set<string>): string {
  let d = dueDate;
  let lead = 0;
  while (lead < 2) {
    d = addDaysStr(d, -1);
    if (!holidaySet.has(d)) lead++;
  }
  while (holidaySet.has(d)) d = addDaysStr(d, -1);
  return d;
}

// ── Due-date reminders (holiday-aware, ~two working days out) ──────────────
// Twice a day, find every open task whose holiday-aware reminder day is today
// and remind the people responsible: each assignee gets their own list (in-app
// notification + email) and the Boss gets a single consolidated list of all
// such tasks across the team. `period` is a human label ("Morning"/"Afternoon").
export async function sendDueDateReminders(
  period: string,
): Promise<{ tasks: number; notified: number; emailed: number }> {
  logger.info({ period }, "Running due-date reminder job");
  const todayStr = ymd(istToday());
  const holidayRows = await db.select().from(holidaysTable);
  // Office is off on full-day and weekend-type holidays; half-days still count
  // as working days, so only those are skipped when counting the 2-day lead.
  const holidaySet = new Set(holidayRows.filter((h) => h.type !== "half").map((h) => h.date));

  const users = await db.select().from(usersTable);
  const userMap = new Map(users.map((u) => [u.id, u]));
  const openTasks = await db
    .select()
    .from(tasksTable)
    .where(and(isNotNull(tasksTable.dueDate), ne(tasksTable.status, "done")));
  // Fire today for every task whose holiday-aware reminder date is today.
  const due = openTasks.filter(
    (task) => task.dueDate != null && reminderDateFor(task.dueDate, holidaySet) === todayStr,
  );

  if (!due.length) {
    logger.info({ period, today: todayStr, tasks: 0 }, "Due-date reminder: nothing due soon");
    return { tasks: 0, notified: 0, emailed: 0 };
  }

  const byAssignee = new Map<number, typeof due>();
  for (const task of due) {
    if (!task.assignedTo) continue;
    const list = byAssignee.get(task.assignedTo);
    if (list) list.push(task);
    else byAssignee.set(task.assignedTo, [task]);
  }

  let notified = 0;
  let emailed = 0;
  const toRow = (task: (typeof due)[number]) => ({
    title: task.title,
    status: task.status,
    priority: task.priority,
    dueDate: task.dueDate,
  });

  // Per-assignee: in-app notification + email.
  for (const [uid, list] of byAssignee) {
    const u = userMap.get(uid);
    if (!u) continue;
    const plural = list.length === 1 ? "task" : "tasks";
    await createNotifications([{
      userId: uid,
      type: "due_reminder",
      message: `Reminder: ${list.length} ${plural} due soon — please complete before the due date.`,
      taskId: list[0].id,
    }]);
    notified++;
    if (u.email) {
      const ok = await sendReminderEmail({
        toEmail: u.email,
        toName: u.name,
        period: `Due Soon (${period})`,
        tasks: list.map(toRow),
      });
      if (ok) emailed++;
      await new Promise((r) => setTimeout(r, 600));
    }
  }

  // Boss / Management: one consolidated list of everything due in 2 days.
  const bosses = users.filter((u) => isBoss(u));
  for (const b of bosses) {
    const plural = due.length === 1 ? "task" : "tasks";
    await createNotifications([{
      userId: b.id,
      type: "due_reminder",
      message: `Team reminder: ${due.length} ${plural} due soon.`,
      taskId: due[0].id,
    }]);
    notified++;
    if (b.email) {
      const ok = await sendReminderEmail({
        toEmail: b.email,
        toName: b.name,
        period: `Team — Due Soon (${period})`,
        tasks: due.map(toRow),
      });
      if (ok) emailed++;
      await new Promise((r) => setTimeout(r, 600));
    }
  }

  logger.info({ period, today: todayStr, tasks: due.length, notified, emailed }, "Due-date reminder complete");
  return { tasks: due.length, notified, emailed };
}

export function startScheduler() {
  const opts = { timezone: SCHEDULER_TZ } as const;
  // Catch-up on boot: node-cron does not replay missed runs, so if the server
  // was down/restarted across a midnight boundary the day's occurrences would
  // never be generated. Running once at startup fills any missed period. The
  // job is idempotent (period-key guard + onConflictDoNothing), so this is safe.
  // Retire the old joke "lunch" tasks first, then run recurring generation so
  // they are not re-cloned. They now live as a dashboard banner + 12/1 PM bell.
  retireLunchTasks()
    .catch((err) => logger.error({ err }, "Lunch task retirement failed"))
    .then(() =>
      cleanupThanePreJulyTasks().catch((err) =>
        logger.error({ err }, "Thane pre-July task cleanup failed"),
      ),
    )
    .then(() =>
      ensureThaneWeeklyTemplates().catch((err) =>
        logger.error({ err }, "Thane weekly template seed failed"),
      ),
    )
    .then(() =>
      ensureSonaliJdTasks().catch((err) =>
        logger.error({ err }, "Sonali JD task seed failed"),
      ),
    )
    .then(() =>
      cleanupOptedOutUserTasks().catch((err) =>
        logger.error({ err }, "Opted-out user task cleanup failed"),
      ),
    )
    .then(() =>
      cleanupNonWorkingDayDailyTasks().catch((err) =>
        logger.error({ err }, "Non-working-day daily task cleanup failed"),
      ),
    )
    .finally(() => {
      generateRecurringTasks().catch((err) =>
        logger.error({ err }, "Boot catch-up recurring generation failed"),
      );
    });
  // Generate recurring occurrences just after midnight IST...
  cron.schedule(
    "5 0 * * *",
    () => {
      void generateRecurringTasks();
    },
    opts,
  );
  // ...then send everyone their combined "today's tasks" digest at 9:00 AM IST.
  // Guarded by a once-per-day claim so it never double-sends alongside the
  // Scheduled Deployment job (see runDailyDigestOnce).
  cron.schedule("0 9 * * *", () => void runDailyDigestOnce(), opts);
  // ...and a daily Dashboard summary to selected people at 9:00 AM IST.
  cron.schedule("0 9 * * *", () => void runDashboardDigestOnce(), opts);
  // Due-date reminders (tasks due in exactly 2 days) twice a day: 10 AM + 3 PM IST.
  cron.schedule("0 10 * * *", () => void sendDueDateReminders("Morning"), opts);
  cron.schedule("0 15 * * *", () => void sendDueDateReminders("Afternoon"), opts);
  // Fun lunch reminders for everyone (in-app bell only): order at 12, eat at 1.
  cron.schedule("0 12 * * *", () => void runLunchReminderOnce("order"), opts);
  cron.schedule("0 13 * * *", () => void runLunchReminderOnce("eat"), opts);
  logger.info("Task scheduler started (boot catch-up + recurring generation + daily digest + due-date reminders + lunch reminders)");
}
