import { pgTable, serial, text, integer, timestamp, boolean, uniqueIndex } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const tasksTable = pgTable(
  "tasks",
  {
    id: serial("id").primaryKey(),
    title: text("title").notNull(),
    description: text("description"),
    assignedTo: integer("assigned_to"),
    assignedBy: integer("assigned_by"),
    dueDate: text("due_date"),
    dueTime: text("due_time"),
    // Human due-date rule for recurring tasks (e.g. "6th of next month",
    // "Every Wednesday", "31 December"). When set, the recurring generator
    // recomputes each new occurrence's due date from this rule + the task type
    // instead of defaulting to the generation day. NULL for ad-hoc tasks.
    dueRule: text("due_rule"),
    priority: text("priority").notNull().default("medium"),
    status: text("status").notNull().default("pending"),
    type: text("type").notNull().default("daily"),
    category: text("category"),
    department: text("department"),
    remark: text("remark"),
    parentTaskId: integer("parent_task_id"),
    // When set, this task is an auto-generated mirror of a Compliance Calendar
    // activity for the period stored in `lastRunDate` (the compliance periodKey).
    // Lets the All Tasks list show compliance activities as real tasks and keeps
    // completion in sync with the per-company compliance grid.
    complianceItemId: integer("compliance_item_id"),
    autoGenerated: boolean("auto_generated").notNull().default(false),
    lastRunDate: text("last_run_date"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    // At most one auto-generated occurrence per parent chain per period.
    // Guarantees "once per period" even if two generation runs overlap.
    uniqueIndex("tasks_parent_period_uq")
      .on(table.parentTaskId, table.lastRunDate)
      .where(sql`parent_task_id IS NOT NULL`),
    // At most one compliance task per compliance item per period — the
    // idempotency guard for the compliance task generator.
    uniqueIndex("tasks_compliance_item_period_uq")
      .on(table.complianceItemId, table.lastRunDate)
      .where(sql`compliance_item_id IS NOT NULL`),
  ]
);

export const insertTaskSchema = createInsertSchema(tasksTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertTask = z.infer<typeof insertTaskSchema>;
export type Task = typeof tasksTable.$inferSelect;
